# Generated by Django 4.2.5 on 2023-09-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackingApp', '0003_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Amount',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='Remark',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='Amount',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='Remark',
            field=models.CharField(max_length=100),
        ),
    ]
